AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sonic DOM Project - Post Traces and Save to S3
Resources:
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.put
      Runtime: nodejs4.3
      CodeUri: ../lambda
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /
            Method: any
            RestApiId: !Ref DomApi
  DomApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
      DefinitionBody: 
        swagger: "2.0"
        info:
          version: "1.0.0"
          title: minimal
          description: Example of the bare minimum Swagger spec
        host: localhost:3000 # otherwise, a random port will be used each time
        paths:
          /:
            put:
              responses:
                "200":
                  description:  Describe the 200 response in more detail
                "500":
                  description:  Describe the 500 response in more detail
        