AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sonic DOM Project - Post Traces and Save to S3
Parameters:
  S3Bucket:
    Description: The S3 bucket to store Traces in.
    Type: String
Resources:
  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dom-api-lambda
      Tags:
        - Name dom-api-lambda

  DomApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: prod
        DefinitionBody:
            swagger: 2.0
            info:
              title: !Ref AWS::StackName
            paths:
              "/":
                x-amazon-apigateway-any-method:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PutFunction.Arn}/invocations
                    responses:
                      default:
                        statusCode: 200
                    passthroughBehavior: when_no_match
                  responses:
                    "200":
                      description:  Describe the 200 response in more detail
            swagger: '2.0'

  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./lambda
      Policies: AmazonS3FullAccess
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /
            Method: any
            RestApiId: !Ref DomApi

  ConfigLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - DomApi
    - PutFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PutFunction
      Principal: apigateway.amazonaws.com